### ISSUE TITLE
how to set config

### ISSUE THREAD

**Issue by lsyoujian** [mukund109/monai#1]
I tried many many times ，the result is
![output](https://user-images.githubusercontent.com/22512152/55797362-c54f1c80-5afe-11e9-9b86-6d6bd45e774e.png)

**Comment by lsyoujian** [comment]
![output](https://user-images.githubusercontent.com/22512152/56202795-66e1eb00-6076-11e9-8e08-725098faf1a2.png)
still not as good as your result

**Comment by mukund109** [comment]
Hi, sorry for the late response. This repo isn't really something that is intended for public use, and I haven't really invested enough time to make the examples reproducible. 

Having said that, for this case you could try doing 'color transfer' before style transfer.

**Comment by lsyoujian** [comment]
![20190510133819](https://user-images.githubusercontent.com/22512152/57504953-29951400-7329-11e9-8caa-3158b5f5ce85.jpg)

Thank you for response.
I need try to do many many times tune parameters by myself and the reuslt is not good,your suggest is very helpful to me.
I have do  color transfer before .But the result is not good enough .



In the picture, up is your result ，down is my result.
The texture and details  is  difference between mine and yours.
By your experience how to optimize the texture and details, tune which parameters?
